version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lala-web
    ports:
      - '3000:3000'
    restart: always
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_XlYq7czvWP1V@ep-bitter-paper-ap8blfnb.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
      - ADMIN_JWT_SECRET=lala-secret-salt-key-2026-dynamic-token-signing
      - NEXT_PUBLIC_WEB3FORMS_ACCESS_KEY=0719f284-576b-40ce-9a59-57554537e65c
      - NODE_ENV=production
    volumes:
      # Persist uploaded videos and images across deploys & restarts
      - lala_assets:/app/public/assets

volumes:
  lala_assets:
    driver: local
